### ISSUE TITLE
Outdated info in README

### ISSUE THREAD

**Issue by wfhartford** [dend/vaccine-appointment-finder#2]
This is amazing, I was working on something similar to bump up my appointment but figured someone else must have done it already.

Your readme states:
> To find a vaccine appointment in British Columbia, and especially if you have one booked - requires canceling the existing one.

I'm guessing this was true when written, but the booking site now lets you browse open slots when you have an appointment and re-schedule quite easily.

This is still a super handy tool to quickly identify openings.

**Comment by dend** [comment]
Good point - recent updates to the experience mitigate that problem. Will update the README.
